name: Doc

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  validate-docs:
    name: Validate Markdown Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if any markdown files changed
        id: check-md-files
        run: |
          CHANGED_MD=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' || true)
          if [ -n "$CHANGED_MD" ]; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
            echo "changed_files<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGED_MD" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Link Checker
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            ${{ steps.changed-markdown-files.outputs.all_changed_files }}
